// Passo 04 - Estilização dos componentes em geral:
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    header: {
        backgroundColor: 'white',
        width: '100%',
        height: 173,
        justifyContent: 'center',
        alignItems: 'center',
    },
    saudacao: {
        color: 'black',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
        marginBottom: 20,
    },
    logo: {
        height: 100,
        resizeMode: 'contain',
    },
    rolagem: {
        marginHorizontal: 1,
    },
    aviso: {
        color: 'rgba(0, 0, 0, 0.5)',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
        marginBottom: 20,
    },
    container: {
        padding: 10,
    },
    livroContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'black',
        borderWidth: 4,
        borderColor: '#9400D3',
        borderRadius: 36,
        padding: 16,
        marginTop: 10,
        marginBottom: 10,
    },
    livroContainerCabecalho: {
        flex: 1,
        //borderWidth: 1,
        borderColor: 'white',
        width: 180,
        height: 140,
        marginBottom: 10,
    },
    livroContainerCapa: {
        borderWidth: 1,
        borderColor: '#9400D3',
        backgroundColor: 'pink', // Esta cor serve apenas para simular a visualização da capa anexada do livro
        width: 100,
        height: 140,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 185,
        marginTop: -24,
        marginBottom: -100,
    },
    livroContainerDescricao: {
        //borderWidth: 1,
        borderColor: 'white',
        width: 285,
        height: 140,
        marginBottom: 10,
    },
    atualizacaoContainer: {
        flexDirection: 'row',
    },
    inputTitulo: {
        flex: 1,
        borderRadius: 6,
        padding: 16,
        fontSize: 16,
        marginRight: 10,
        marginBottom: 10,
        marginTop: 10,
        borderColor: 'black',
        borderWidth: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    inputUpdateTitulo: {
        flex: 1,
        color: 'white',
        borderRadius: 6,
        padding: 16,
        fontSize: 16,
        marginRight: 10,
        marginBottom: 10,
        marginTop: 10,
        borderColor: 'white',
        borderWidth: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    titulo: {
        color: 'white',
        fontFamily: 'Roboto',
        fontWeight: 'bold',
        fontSize: 15,
    },
    inputSinopse: {
        marginBottom: 10,
        borderRadius: 6,
        padding: 16,
        fontSize: 16,
        borderColor: 'black',
        borderWidth: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    inputUpdateSinopse: {
        color: 'white',
        marginBottom: 10,
        borderRadius: 6,
        padding: 16,
        fontSize: 16,
        borderColor: 'white',
        borderWidth: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    sinopse: {
        color: 'white',
        fontFamily: 'Roboto',
        fontSize: 15,
    },
    imagemCapa: {
        width: 100,
        height: 140,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    botaoAnexarImg: {
        backgroundColor: 'black',
        width: 80,
        height: 62,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    botaoAtualizarAnexoImg: {
        backgroundColor: 'white',
        width: 80,
        height: 62,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
    },
    textoBotaoAnexarImg: {
        color: 'white',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    textoAtualizarAnexoImg: {
        color: 'black',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    botaoCadastrar: {
        width: 300,
        height: 60,
        borderRadius: 60,
        backgroundColor: '#9400D3',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 1,
        flexDirection: 'row',
        marginLeft: 15,
        marginBottom: 20,
    },
    textoBotaoCadastrar: {
        color: 'white',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
        fontSize: 17,
    },
    linhaDivisoria: {
        borderBottomWidth: 2,
        borderBottomColor: 'rgba(0, 0, 0, 0.5)',
        marginVertical: 10,
    },
    botaoEditar: {
        width: 90,
        height: 60,
        borderRadius: 100,
        backgroundColor: '#F0BE00',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 1,
        marginRight: 30,
    },
    textoBotaoEditar: {
        color: 'black',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    botaoExcluir: {
        width: 90,
        height: 60,
        borderRadius: 100,
        backgroundColor: '#BB0E22',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 1,
        marginLeft: 30,
    },
    textoBotaoExcluir: {
        color: 'white',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    botaoAtualizar: {
        width: 300,
        height: 60,
        borderRadius: 60,
        backgroundColor: '#9400D3',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 1,
    },
    textoBotaoAtualizar: {
        color: 'white',
        fontFamily: 'Roboto',
        textAlign: 'center',
        fontWeight: 'bold',
        fontSize: 17,
    },
});  